import "@/styles/globals.css";
import {GeistSans} from 'geist/font/sans';
import {GeistMono} from 'geist/font/mono';
import {SiteHeader} from "@/components/ui/site-header";
import {ThemeProvider} from "next-themes";

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{rel: "icon", url: "/favicon.ico"}],
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body
            className={`w-screen h-screen overflow-x-hidden dark:bg-background-dark bg-background font-sans ${GeistSans.variable} ${GeistMono.variable}`}>
        <ThemeProvider attribute="class"
                       defaultTheme="system"
                       enableSystem
                       disableTransitionOnChange>
            <SiteHeader/>
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
